using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CSCodeChallenges
{
    internal class FibonacciEvenSum
    {
        static void Main(string[] args)
        {
            //Each new term in the Fibonacci sequence is generated by adding the previous two terms.  By starting with 1 and 2, the first 10 temrs will be:
            //1,2,3,5,8,13,21,34,55,89,...
            //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

            int sum = 2;
            //int num1 = 1;
            int num1 = 2;
            int num2 = 3;
            int nextNum = 0;
            while (nextNum < 4_000_000)
            {
               
                nextNum = num1 + num2;

                if (nextNum % 2 == 0)
                {
                    sum += nextNum;
                }


                num1 = num2;
                num2 = nextNum;
            }

            Console.WriteLine($"The sum of all the even-valued terms under 4,000,000 in the Fibonacci Sequence is {sum}");
        }
    }
}
